#!/usr/bin/env python3
"""Phase 4 — Fidelity Gate (CGProj).

Proves checked-in generated artifacts are provably downstream of source metadata (anti-drift):
each artifact byte-matches the freshly-rendered output AND embeds a content-hash equal to the
content_hash recomputed from current metadata.

ANTI-VACUITY: the gate compares ON-DISK bytes vs FRESHLY-GENERATED bytes (never output-vs-itself),
and proves it can detect drift via controls that run through the SAME comparator the real check
uses:
  positive control  — real artifacts match (live assertion).
  neg control 1      — body tamper (real on-disk byte flip) -> byte-match FAIL.
  neg control 2      — hash tamper (alter one hex char)      -> embedded-hash-match FAIL.
  neg control 3      — stale-metadata drift (mutated metadata vs unchanged disk) -> FAIL.
  vacuity guard      — >=1 artifact compared, each with a present 64-hex embedded hash.

Run from repo root:  python phase4_fidelity_gate.py <repo_dir>
Exit 0 = PASS; nonzero = FAIL (fails closed; regenerate artifacts from metadata).
"""
import sys, os, re, hashlib

PY = sys.executable
REPO = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else ".")
sys.path.insert(0, REPO)

results = []
def check(name, ok, detail=""):
    results.append((name, ok))
    line = "  " + ("PASS" if ok else "FAIL") + "  " + name
    if detail:
        line += " — " + detail
    print(line)

from ugk.projections import generate as G
from ugk.projections import hash as H

GEN_DIR = os.path.join(REPO, "ugk", "projections", "generated")
_HASH_RE = re.compile(r"^content-hash:\s*([0-9a-f]{64})\s*$", re.M)


# ---- the single shared comparator (real check AND controls call this) ----
def fidelity_compare(name, on_disk_bytes, *, expected_text=None):
    """Compare on-disk artifact bytes against freshly-generated expected bytes.

    Returns dict with byte_match, embedded_hash, recomputed_hash, hash_match, hash_wellformed.
    expected_text defaults to generate_artifact(name) — the SINGLE producer. A control may pass a
    mutated-metadata expected_text to exercise stale-drift through this same comparator.
    """
    if expected_text is None:
        expected_text = G.generate_artifact(name)
    expected_bytes = expected_text.encode("utf-8")
    byte_match = (on_disk_bytes == expected_bytes)
    text = on_disk_bytes.decode("utf-8", errors="replace")
    m = _HASH_RE.search(text)
    hash_wellformed = m is not None
    embedded = m.group(1) if m else None
    recomputed = H.content_hash()
    hash_match = (embedded == recomputed) if embedded else False
    return {
        "byte_match": byte_match,
        "embedded_hash": embedded,
        "recomputed_hash": recomputed,
        "hash_match": hash_match,
        "hash_wellformed": hash_wellformed,
    }


def read_bytes(name):
    with open(os.path.join(GEN_DIR, name), "rb") as f:
        return f.read()


# ---- vacuity guard: artifacts exist and were actually compared ----
present = [n for n in G.ARTIFACTS if os.path.exists(os.path.join(GEN_DIR, n))]
check("vacuity guard: >=1 generated artifact present and compared",
      len(present) >= 1 and len(present) == len(G.ARTIFACTS),
      "present=" + str(len(present)) + "/" + str(len(G.ARTIFACTS)) + " " + str(present))

# ---- POSITIVE CONTROL / real check: every artifact byte-matches + hash-matches ----
pos_ok = True
for name in G.ARTIFACTS:
    r = fidelity_compare(name, read_bytes(name))
    ok = r["byte_match"] and r["hash_match"] and r["hash_wellformed"]
    pos_ok = pos_ok and ok
    check("positive: " + name + " byte-match + embedded-hash-match",
          ok, "byte_match=" + str(r["byte_match"]) + " hash_match=" + str(r["hash_match"])
          + " hash=" + (r["embedded_hash"][:12] + "…" if r["embedded_hash"] else "MISSING"))

# ---- NEG 1: body tamper (real on-disk byte flip in the body, not the header) -> byte FAIL ----
name0 = next(iter(G.ARTIFACTS))
disk0 = read_bytes(name0)
# flip a byte well past the header (after the closing '-->\n')
hdr_end = disk0.index(b"-->\n") + 4
flip_at = hdr_end + 20
tampered_body = bytearray(disk0)
tampered_body[flip_at] = tampered_body[flip_at] ^ 0x20  # flip a bit -> different byte
r_body = fidelity_compare(name0, bytes(tampered_body))
check("neg-1 (teeth): body tamper -> byte-match FAILS",
      r_body["byte_match"] is False,
      "byte_match=" + str(r_body["byte_match"]) + " (must be False)")

# ---- NEG 2: hash tamper (alter one hex char of the embedded content-hash) -> hash FAIL ----
text0 = disk0.decode("utf-8")
m0 = _HASH_RE.search(text0)
good_hash = m0.group(1)
bad_char = "0" if good_hash[0] != "0" else "1"
bad_hash = bad_char + good_hash[1:]
tampered_hash_text = text0.replace("content-hash: " + good_hash, "content-hash: " + bad_hash, 1)
r_hash = fidelity_compare(name0, tampered_hash_text.encode("utf-8"))
check("neg-2 (teeth): hash tamper -> embedded-hash-match FAILS",
      r_hash["hash_match"] is False and r_hash["hash_wellformed"] is True,
      "hash_match=" + str(r_hash["hash_match"]) + " wellformed=" + str(r_hash["hash_wellformed"]))

# ---- NEG 3: stale-metadata drift (mutated metadata vs UNCHANGED on-disk artifact) -> FAIL ----
# Mutate metadata in memory (change one pattern title), regenerate EXPECTED with the same producer,
# compare against the UNCHANGED on-disk bytes. This is the central drift scenario.
import dataclasses
from ugk.projections import patterns as P
orig_patterns = P.PATTERNS
mutated = list(orig_patterns)
mutated[0] = dataclasses.replace(mutated[0], title=mutated[0].title + " (DRIFTED)")
# build expected text from MUTATED metadata using the same render path the producer uses
from ugk.projections import render as _R
def _expected_from_mutated(name):
    # mirror generate_artifact but with mutated patterns for the patterns artifact
    from ugk.projections import hash as _H
    label, _fn = G.ARTIFACTS[name]
    if label == "patterns":
        body = _R.render_patterns(patterns=tuple(mutated))
    else:
        body = _R.render_domain_mappings()
    # header uses content_hash of MUTATED metadata so the drift is realistic end-to-end
    hdr = ("<!-- CGPROJ-PROVENANCE\n"
           "projection-identity: " + _H.PROJECTION_IDENTITY + "\n"
           "content-hash: " + _H.content_hash(patterns=tuple(mutated)) + "\n"
           "renderer-version: " + _H.RENDERER_VERSION + "\n-->\n")
    return hdr + "\n" + body
r_stale = fidelity_compare(name0, read_bytes(name0), expected_text=_expected_from_mutated(name0))
# guard: the mutation actually changed expected output (else the control is vacuous)
mutation_changed = (_expected_from_mutated(name0).encode("utf-8") != G.generate_artifact(name0).encode("utf-8"))
check("neg-3 (teeth): stale-metadata drift (mutated metadata vs unchanged disk) -> FAILS",
      mutation_changed and (r_stale["byte_match"] is False),
      "mutation_changed_expected=" + str(mutation_changed) + " byte_match=" + str(r_stale["byte_match"]) + " (must be False)")

ok = all(r[1] for r in results)
print("\n  content_hash (current metadata) = " + H.content_hash())
print("  PHASE 4 FIDELITY GATE: " + ("PASS" if ok else "FAIL — STOP, regenerate from metadata"))
sys.exit(0 if ok else 1)
