#!/usr/bin/env python3
"""Generate docs/index.md — a navigable index of the UGK documentation (deterministic, stdlib-only).

docs/index.md is GENERATED. Do not hand-edit it. It auto-discovers the documentation surface
(root-level *.md + docs/**/*.md) so it cannot silently go stale: add a doc and regenerate.
    python docs_index_gen.py            # write docs/index.md
    python docs_index_gen.py --check    # exit 1 if it would change
This is navigation. Each entry links to the authoritative document; the index carries no authority.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SELF = "docs/index.md"
# the core navigation set, in intended reading order
START = ["README.md", "GLOSSARY.md", "IMPLEMENTATION_CODEX.md", "INVARIANT_TAXONOMY.md", "SKILL.md"]
SUBDIR_TITLES = {
    "architecture": "Architecture", "doctrine": "Doctrine", "domain-mappings": "Domain mappings",
    "papers": "Papers", "patterns": "Patterns", "provenance": "Provenance",
}


def _scope():
    """All in-scope documentation files (root *.md + docs/**/*.md), excluding the index itself."""
    files = sorted(p for p in ROOT.glob("*.md"))
    files += sorted(p for p in (ROOT / "docs").rglob("*.md"))
    out = []
    for p in files:
        rel = p.relative_to(ROOT).as_posix()
        if rel == SELF:
            continue
        out.append(rel)
    return out


def _title_and_blurb(rel):
    title, blurb = rel.rsplit("/", 1)[-1], ""
    try:
        lines = (ROOT / rel).read_text(encoding="utf-8", errors="replace").splitlines()
    except Exception:
        return title, blurb
    for ln in lines:
        s = ln.strip()
        if s.startswith("# "):
            title = s[2:].strip()
            break
    for ln in lines:
        s = ln.strip()
        if not s or s.startswith("#") or s.startswith("![") or s.startswith("[![") \
           or s.startswith("```") or s.startswith("|") or s.startswith(">"):
            continue
        blurb = s.strip().lstrip("*_ ").rstrip("*_ ").strip()
        if len(blurb) > 140:
            blurb = blurb[:137].rstrip() + "..."
        break
    return title, blurb


def _link(rel):
    # links are relative to docs/index.md (which lives in docs/)
    if rel.startswith("docs/"):
        return rel[len("docs/"):]
    return "../" + rel


def generate() -> str:
    scope = _scope()
    root_md = [r for r in scope if "/" not in r]
    docs_root = [r for r in scope if r.startswith("docs/") and r.count("/") == 1]
    docs_sub = {}
    for r in scope:
        if r.startswith("docs/") and r.count("/") >= 2:
            docs_sub.setdefault(r.split("/")[1], []).append(r)

    L = ["# UGK documentation — index", ""]
    L.append("**Generated by `docs_index_gen.py`. Do not hand-edit.** A navigable map of every UGK document. "
             "Each entry links to the authoritative file; this index is navigation, not authority. "
             f"Covers {len(scope)} documents.")
    L.append("")

    def section(title, items):
        if not items:
            return
        L.append(f"## {title}")
        L.append("")
        for rel in items:
            t, b = _title_and_blurb(rel)
            line = f"- [{t}]({_link(rel)})"
            if b:
                line += f" — {b}"
            L.append(line)
        L.append("")

    # Start here (intended order), then the rest of root, then docs subdirs, then docs root
    start = [r for r in START if r in root_md]
    section("Start here", start)
    section("Project & reference", [r for r in root_md if r not in start])
    for sub in sorted(docs_sub):
        section(SUBDIR_TITLES.get(sub, sub), sorted(docs_sub[sub]))
    section("Release & schema notes", sorted(docs_root))
    return "\n".join(L) + "\n"


def main() -> int:
    out = ROOT / "docs" / "index.md"
    content = generate()
    if "--check" in sys.argv:
        cur = out.read_text(encoding="utf-8") if out.exists() else ""
        if cur != content:
            print("docs/index.md is stale — run: python docs_index_gen.py")
            return 1
        print("docs/index.md is current.")
        return 0
    out.parent.mkdir(exist_ok=True)
    out.write_text(content, encoding="utf-8")
    print(f"docs/index.md written ({len(content.splitlines())} lines, {len(_scope())} docs indexed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
